/**
 * ast-grep adapter (#64).
 *
 * ast-grep (https://ast-grep.github.io/) runs structural rules against
 * source files and emits per-match JSON. We invoke the binary as an
 * external process; missing binaries are a soft failure.
 *
 * Rule sourcing
 * -------------
 * ast-grep's `--rule` flag takes a single rule *file* and can't be
 * repeated, so a directory of rules (loctx's bundled set, or a
 * user-configured dir) can't go through `--rule` — that failed on every
 * scan with "Is a directory". Rules therefore go through the project
 * config path: a generated `sgconfig.yml` whose `ruleDirs` points at the
 * configured dirs, passed via `--config` (#ast-grep-rules).
 *
 * Output parsing
 * --------------
 * `ast-grep scan --json --config <sgconfig.yml> <file>` emits an array
 * of matches:
 *
 *   [ { "ruleId": "no-eval",
 *       "severity": "error",
 *       "message": "...",
 *       "metadata": { "category": "security" },
 *       "range": { "start": { "line": N }, "end": { "line": M } } } ]
 *
 * Lines in ast-grep are 0-indexed; we convert to 1-indexed to match
 * the rest of the codebase.
 */

import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileAsync as exec } from "../proc.js";
import {
  capFindings,
  detectCommand,
  normalizeSeverity,
  type RulePackFileResult,
  type RulePackFinding,
} from "./rule-pack.js";

// Bumped 1 → 2 when the invocation moved from the broken `--rule <dir>`
// to `--config <sgconfig.yml>`. The version is part of the enrichment
// dedup key, so bumping it re-enqueues every ast-grep record — the
// ~10k rows that failed under the old invocation get re-run (and now
// succeed) on the next backfill/reconcile instead of staying failed.
export const AST_GREP_VERSION = 2;

/**
 * Generate (once per unique ruleDirs set, cached for the process) a
 * minimal `sgconfig.yml` pointing `ruleDirs` at the configured dirs, and
 * return its path for `--config`. Cached so the per-file scan doesn't
 * rewrite the file thousands of times. Paths are double-quoted so dirs
 * with spaces (e.g. macOS "Application Support") stay valid YAML.
 */
const sgConfigCache = new Map<string, string>();

export function sgConfigForRuleDirs(ruleDirs: ReadonlyArray<string>): string {
  const key = [...ruleDirs].sort().join("\n");
  const cached = sgConfigCache.get(key);
  if (cached !== undefined) return cached;
  const hash = createHash("sha1").update(key).digest("hex").slice(0, 16);
  const dir = join(tmpdir(), `loctx-astgrep-${hash}`);
  mkdirSync(dir, { recursive: true });
  const path = join(dir, "sgconfig.yml");
  const body = `# generated by loctx — ast-grep rule sources\nruleDirs:\n${ruleDirs
    .map((d) => `  - ${JSON.stringify(d)}`)
    .join("\n")}\n`;
  writeFileSync(path, body);
  sgConfigCache.set(key, path);
  return path;
}

/**
 * Absolute path to loctx's bundled ast-grep starter rules (shipped to
 * dist/rules/ast-grep by copy-assets). Used as the default rule source when
 * the user hasn't configured their own — ast-grep has no community registry,
 * so loctx ships a small high-signal starter set (editable / overridable).
 */
export function bundledAstGrepRulesDir(): string {
  return fileURLToPath(new URL("../rules/ast-grep", import.meta.url));
}

export async function detectAstGrep(command = "ast-grep"): Promise<string | null> {
  // Rust binary — starts fast, so a tight timeout is enough.
  return detectCommand(command, 2000);
}

export interface RunAstGrepOptions {
  readonly command: string;
  readonly ruleDirs: ReadonlyArray<string>;
  readonly maxFindingsPerFile: number;
  readonly timeoutMs?: number;
}

export async function runAstGrep(
  filePath: string,
  opts: RunAstGrepOptions,
  signal?: AbortSignal,
): Promise<RulePackFileResult> {
  if (opts.ruleDirs.length === 0) {
    return Object.freeze({
      analyzer: "ast-grep",
      toolVersion: "",
      findings: Object.freeze<RulePackFinding[]>([]),
    });
  }
  // `--config <sgconfig.yml>`, NOT `--rule <dir>`: ast-grep's `--rule`
  // takes exactly one rule file and can't repeat, so a rule directory
  // has to go through the project config.
  const args = ["scan", "--json", "--config", sgConfigForRuleDirs(opts.ruleDirs), filePath];
  // `signal` flows from the queue's per-task abort; aborting kills the
  // ast-grep subprocess so a timeout reliably reclaims resources
  // (#197).
  const { stdout } = await exec(opts.command, args, {
    timeout: opts.timeoutMs ?? 30_000,
    maxBuffer: 16 * 1024 * 1024,
    ...(signal !== undefined ? { signal } : {}),
  });
  return parseAstGrepJson(stdout, opts.maxFindingsPerFile);
}

interface AstGrepMatch {
  ruleId?: unknown;
  rule_id?: unknown;
  severity?: unknown;
  message?: unknown;
  metadata?: { category?: unknown } | unknown;
  range?: {
    start?: { line?: unknown } | unknown;
    end?: { line?: unknown } | unknown;
  };
}

export function parseAstGrepJson(json: string, cap: number): RulePackFileResult {
  let parsed: unknown;
  try {
    parsed = JSON.parse(json);
  } catch {
    return Object.freeze({
      analyzer: "ast-grep",
      toolVersion: "",
      findings: Object.freeze<RulePackFinding[]>([]),
    });
  }
  const matches: AstGrepMatch[] = Array.isArray(parsed)
    ? (parsed as AstGrepMatch[])
    : Array.isArray((parsed as { matches?: unknown }).matches)
      ? (parsed as { matches: AstGrepMatch[] }).matches
      : [];
  const out: RulePackFinding[] = [];
  for (const m of matches) {
    const ruleId =
      typeof m.ruleId === "string" ? m.ruleId : typeof m.rule_id === "string" ? m.rule_id : "";
    if (ruleId === "") continue;
    const range = m.range;
    if (range === undefined) continue;
    const lineFrom = readLine(range.start);
    const lineTo = readLine(range.end);
    if (lineFrom === null || lineTo === null) continue;
    const message = typeof m.message === "string" ? m.message : "";
    const severity = normalizeSeverity(m.severity);
    const meta = (m.metadata ?? {}) as { category?: unknown };
    const category = typeof meta.category === "string" ? meta.category : "";
    // ast-grep reports 0-indexed lines; bump to 1-indexed for parity
    // with the rest of the codebase (lizard, duplicates, FTS).
    out.push(
      Object.freeze({
        ruleId,
        severity,
        message,
        category,
        lineFrom: lineFrom + 1,
        lineTo: lineTo + 1,
      }),
    );
  }
  return Object.freeze({
    analyzer: "ast-grep",
    toolVersion: "",
    findings: Object.freeze(capFindings(out, cap)),
  });
}

function readLine(node: unknown): number | null {
  if (typeof node === "object" && node !== null) {
    const v = (node as { line?: unknown }).line;
    if (typeof v === "number" && Number.isFinite(v)) return v;
  }
  return null;
}
